Category.create({"name" => "Characters", "question_bank" => "Q1"})
Category.create({"name" => "Films","question_bank" => "Q2"})
Category.create({"name" => "Planets", "question_bank" => "Q3"})
Category.create({"name" => "Species", "question_bank" => "Q4"})
Category.create({"name" => "Starships", "question_bank" => "Q5"})
